name = "team-mimh-feedback-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "team-mimh-feedback"
database_id = "1641a7bd-84cb-4332-a295-b1b4d837eeb7"  # Replace with your actual D1 database ID

[vars]
ENVIRONMENT = "production"
