name = "feedback-backend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "team-mimh-feedback"
database_id = "1641a7bd-84cb-4332-a295-b1b4d837eeb7"

[vars]
ENVIRONMENT = "production"
